import { mutation } from "./_generated/server";
import { requireAdmin } from "./authHelpers";

/** One-time seed: import Square bookings */
export const seedSquareBookings = mutation({
  handler: async (ctx) => {
    await requireAdmin(ctx);
    const bookings = [
      {
        squareBookingId: "bxe9vrerew29z5",
        customerName: "John Berger Berger",
        serviceName: "Membership Maintenance Essentials – Inside/Out",
        date: "2026-03-21",
        time: "12:10",
        duration: 255,
        status: "confirmed" as const,
        address: "7514 Bluestar Lane",
        city: "Charlotte",
        state: "NC",
        zip: "28226",
        note: "X5 Gate code is # then 0606",
      },
      {
        squareBookingId: "724xg14hvjhfjo",
        customerName: "Bonika Wilson",
        serviceName: "Membership Maintenance Essentials – Inside/Out",
        date: "2026-03-23",
        time: "10:00",
        duration: 150,
        status: "confirmed" as const,
        address: "6501 Glynmoor Lakes Drive",
        city: "Charlotte",
        state: "NC",
        zip: "28277",
      },
      {
        squareBookingId: "ghn9ik2vgmtfmd",
        customerName: "Sean Clark",
        serviceName: "Standard Inside & Out",
        date: "2026-03-23",
        time: "12:30",
        duration: 205,
        status: "confirmed" as const,
        address: "12201 Steele Creek Road",
        city: "Charlotte",
        state: "NC",
        zip: "28273",
        note: "On-site contact is Ken Carter, 704-418-1768",
      },
      {
        squareBookingId: "rjg04v5217r0at",
        customerName: "Natalie Arita",
        serviceName: "Inspection",
        date: "2026-03-24",
        time: "10:00",
        duration: 30,
        status: "confirmed" as const,
        address: "1117 Hoyle Lane",
        city: "Waxhaw",
        state: "NC",
        zip: "28173",
      },
      {
        squareBookingId: "rlqm4dnsxmgj82",
        customerName: "Justin gilmore",
        serviceName: "Standard Inside & Out",
        date: "2026-03-24",
        time: "10:30",
        duration: 235,
        status: "confirmed" as const,
        address: "1207 Glynwater Ln",
        city: "Waxhaw",
        state: "NC",
        zip: "28173",
        note: "I have points to use. ",
      },
      {
        squareBookingId: "634y7kqxbp0yr8",
        customerName: "Jerry Smith",
        serviceName: "Membership Maintenance Essentials – Inside/Out",
        date: "2026-03-30",
        time: "10:00",
        duration: 150,
        status: "confirmed" as const,
        address: "1709 Tranquility blvd",
        city: "Lancaster",
        state: "SC",
        zip: "29720",
      },
      {
        squareBookingId: "3a8jd0d0sh4h8z",
        customerName: "Jerry Smith",
        serviceName: "Membership Maintenance Essentials – Inside/Out",
        date: "2026-03-30",
        time: "12:30",
        duration: 150,
        status: "confirmed" as const,
        address: "1709 Tranquility blvd",
        city: "Lancaster",
        state: "SC",
        zip: "29720",
      },
      {
        squareBookingId: "manual-2026-03-30-1500",
        customerName: "Kevin Watson",
        serviceName: "Standard Exterior Only",
        date: "2026-03-30",
        time: "15:00",
        duration: 100,
        status: "confirmed" as const,
        address: "",
        city: "",
        state: "",
        zip: "",
      },
      {
        squareBookingId: "manual-2026-04-01-1000",
        customerName: "Brian McCarron",
        serviceName: "Membership Maintenance Essentials – Inside/Out",
        date: "2026-04-01",
        time: "10:00",
        duration: 165,
        status: "confirmed" as const,
        address: "",
        city: "",
        state: "",
        zip: "",
      },
      {
        squareBookingId: "manual-2026-04-07-1000",
        customerName: "Andrea K Guzinski",
        serviceName: "Membership Maintenance Essentials – Inside/Out",
        date: "2026-04-07",
        time: "10:00",
        duration: 105,
        status: "confirmed" as const,
        address: "",
        city: "",
        state: "",
        zip: "",
      },
      {
        squareBookingId: "manual-2026-04-07-1145",
        customerName: "Andrea K Guzinski",
        serviceName: "Membership Maintenance Essentials – Inside/Out",
        date: "2026-04-07",
        time: "11:45",
        duration: 105,
        status: "pending" as const,
        address: "",
        city: "",
        state: "",
        zip: "",
      },
      {
        squareBookingId: "manual-2026-04-14-1200",
        customerName: "Peter Borans",
        serviceName: "Membership Maintenance Essentials – Inside/Out",
        date: "2026-04-14",
        time: "12:00",
        duration: 105,
        status: "confirmed" as const,
        address: "",
        city: "",
        state: "",
        zip: "",
      },
      {
        squareBookingId: "manual-2026-04-15-1200",
        customerName: "Andrew Laster",
        serviceName: "Membership Maintenance Essentials – Inside/Out",
        date: "2026-04-15",
        time: "12:00",
        duration: 120,
        status: "confirmed" as const,
        address: "",
        city: "",
        state: "",
        zip: "",
      },
      {
        squareBookingId: "9q4qxtjwe8g4iz",
        customerName: "Ben Brown",
        serviceName: "Ceramic Maintenance Cleaning",
        date: "2026-04-24",
        time: "10:30",
        duration: 30,
        status: "confirmed" as const,
        address: "2333 Laburnum Ave",
        city: "Charlotte",
        state: "NC",
        zip: "28205",
      },
      {
        squareBookingId: "62fuh10xeqv0tf",
        customerName: "Andrea K Guzinski",
        serviceName: "Membership Maintenance Essentials – Inside/Out",
        date: "2026-05-05",
        time: "10:00",
        duration: 105,
        status: "confirmed" as const,
        address: "2620 Waxhaw Marvin Rd",
        city: "Waxhaw",
        state: "NC",
        zip: "28173",
      },
      {
        squareBookingId: "vctnuan8tbkb39",
        customerName: "Peter Borans",
        serviceName: "Membership Maintenance Essentials – Inside/Out",
        date: "2026-05-12",
        time: "12:00",
        duration: 105,
        status: "pending" as const,
        address: "604 Sorrell Spring Court ",
        city: "Waxhaw",
        state: "NC",
        zip: "28173",
      },
      {
        squareBookingId: "b0y24tjouokcmi",
        customerName: "Andrew Laster",
        serviceName: "Membership Maintenance Essentials – Inside/Out",
        date: "2026-05-13",
        time: "12:00",
        duration: 120,
        status: "confirmed" as const,
        address: "2000 Crane Rd",
        city: "Charlotte",
        state: "NC",
        zip: "28173",
      },
      {
        squareBookingId: "y1jx936sy50a4a",
        customerName: "Ben Brown",
        serviceName: "Ceramic Maintenance Cleaning",
        date: "2026-05-22",
        time: "10:30",
        duration: 30,
        status: "confirmed" as const,
        address: "2333 Laburnum Ave",
        city: "Charlotte",
        state: "NC",
        zip: "28205",
      },
      {
        squareBookingId: "xtb7dwfq85we7m",
        customerName: "Andrea K Guzinski",
        serviceName: "Membership Maintenance Essentials – Inside/Out",
        date: "2026-06-02",
        time: "10:00",
        duration: 105,
        status: "confirmed" as const,
        address: "2620 Waxhaw Marvin Rd",
        city: "Waxhaw",
        state: "NC",
        zip: "28173",
      },
      {
        squareBookingId: "8q1rr197xrqzkx",
        customerName: "Peter Borans",
        serviceName: "Membership Maintenance Essentials – Inside/Out",
        date: "2026-06-10",
        time: "12:00",
        duration: 105,
        status: "confirmed" as const,
        address: "604 Sorrell Spring Court ",
        city: "Waxhaw",
        state: "NC",
        zip: "28173",
      },
      {
        squareBookingId: "mij2tkrwiwn2fd",
        customerName: "Andrew Laster",
        serviceName: "Membership Maintenance Essentials – Inside/Out",
        date: "2026-06-17",
        time: "12:00",
        duration: 120,
        status: "confirmed" as const,
        address: "2000 Crane Rd",
        city: "Charlotte",
        state: "NC",
        zip: "28173",
      },
      {
        squareBookingId: "s359vr50a98wwx",
        customerName: "Ben Brown",
        serviceName: "Ceramic Maintenance Cleaning",
        date: "2026-06-19",
        time: "10:30",
        duration: 30,
        status: "confirmed" as const,
        address: "2333 Laburnum Ave",
        city: "Charlotte",
        state: "NC",
        zip: "28205",
      },
    ];

    let created = 0;
    let skipped = 0;

    for (const b of bookings) {
      // Dedup by squareBookingId
      const existing = await ctx.db
        .query("bookings")
        .withIndex("by_square_booking_id", (q) => q.eq("squareBookingId", b.squareBookingId))
        .first();
      if (existing) { skipped++; continue; }

      const fullAddr = b.address ? `${b.address}, ${b.city}, ${b.state} ${b.zip}` : `${b.city}, ${b.state} ${b.zip}`;
      const code = `SQ-${b.squareBookingId.slice(0, 8).toUpperCase()}`;

      await ctx.db.insert("bookings", {
        customerName: b.customerName,
        customerPhone: "",
        customerEmail: "",
        serviceAddress: fullAddr,
        zipCode: b.zip || undefined,
        serviceName: b.serviceName,
        price: 0,
        date: b.date,
        time: b.time,
        status: b.status,
        paymentStatus: "unpaid",
        confirmationCode: code,
        notes: b.note || `Imported from Square. Duration: ${b.duration}min`,
        squareBookingId: b.squareBookingId,
        totalDuration: b.duration,
      });
      created++;
    }

    return { created, skipped, total: bookings.length };
  },
});